4 navs for guest
abemscac/inet-PatrickKuei pull request #7
Opened 2022-04-29 06:12 UTC by PatrickKuei

Close #4 

阿斯 馬上就來發ＰＲ史蒂芬哥
最近我司要進入新的開發週期 又要進去看那些狗屎糞扣跟模仿他們的狗屎糞扣了
我到現在都不知道我們團隊的分工方式
之前有時候是PM開jira ticket給我 有時候是data team負責開spec的人開ticket
也不知道他們怎麼去拆整個feature需要哪些story 又能拆分成哪些task
照之前經驗看起來像是工程師自己想辦法 漏了才東補西補
希望是我誤會了

再麻煩史蒂芬哥您幫我review了

2022-04-29 06:22 UTC, PatrickKuei commented
報告史蒂芬哥
我們PR Commit check all fail
太神了吧
看起來好像都是卡在安裝node那一步
不曉得是不是哪個設定檔被我搞壞了

2022-04-29 06:34 UTC, abemscac commented
原來如此patrick哥
看來貴公司的PM等等管理階層也是德不配位
鬼島職場=政治圈  位子越高越愛亂搞
搞的越差升官越快

那些檢查失敗應該是因為package-lock.json的關係
我們的github actions裡面是用`yarn install`，yarn不喜歡npm install遺留下來的產物
您可以選擇把package-lock.json刪掉，或是把`.github/workflows/pr-commit.yaml`裡面的`yarn install`都改成`npm install`，兩種應該都能修好
感謝patrick哥

2022-04-29 13:13 UTC, abemscac commented
報告patrick哥
看來npm install和yarn install都因為東方神祕力量卡住了
我晚點看看  也許要等到星期天了

2022-04-29 13:15 UTC, abemscac commented
希望這個小愛心可以把它修好patrick哥
修復一切  世界和平
https://i.redd.it/5sls86capfw81.jpg

2022-04-30 14:48 UTC, abemscac commented on .eslintrc.json
> +    "jest/globals": true
需要做幾件事才能順利把eslint和jest合在一起用：
- 加上這一行 `"jest/globals": true`
- 裝 `eslint-plugin-jest`
- 建 `jest.config.ts` (或.js)，裡面加上一些設定
- 下面 `plugins` 陣列多加一個 `"jest"`

2022-05-01 02:54 UTC, abemscac requested changes
報告patrick哥
看起來還OK，也許等您做到第2個畫面之後整體的程式碼就會成形了
有些動畫的東西等之後再跟您細細說明，感謝patrick哥

2022-05-01 02:54 UTC, abemscac commented on src/components/Home.tsx
> +      </div>
## 已知問題

目前在您的實作中看見幾個問題：

![Screen Shot 2022-05-01 at 8 31 46 AM](https://user-images.githubusercontent.com/59676941/166128335-53c42f2f-3e9c-4e4f-ac4d-018e5ff274eb.png)

寬度為800px的時候：

1. navbar右邊的兩個按鈕分別和search-bar還有邊邊黏在一起，sign up的字也因為他認為寬度不夠的關係換行了
  - 螢幕縮小之後東西黏在一起主要是layout導致的，請見下方的layout指引
  - 換行的問題可以在按鈕上面用 `white-space: nowrap` 解決
2. navbar中間search-bar的字會蓋在icon上面
  - 用div(container)把input和icon包起來是對的
  - 我們可以把container變成橫向的flexbox (`align-items: center`也可以順便加)，這樣input的字就永遠不會蓋到icon
  - 就算之後左邊的input需要做很多怪效果，我們可以直接修改左邊(例如：包一個relative的div)，右邊的icon一樣不會被蓋住
3. navmenu item的排版挺怪的，目前是直接給icon一個寬度
    ![Screen Shot 2022-05-01 at 8 34 47 AM](https://user-images.githubusercontent.com/59676941/166128785-e183907e-3031-4fe4-89e1-b7613e9ec389.png)
    不過您的考慮是合理的，也許您擔心icon的尺寸不一樣，會造成每個選項的圖案和字都在不同的位子
    在navmenu裡面所有的icon都是相同大小的，所以建議您用margin的方式來處理即可 (規則：margin用來處理element和element之間的間隔，padding用來處理element裡面最邊界的內容(最上/最下/最左/最右)和對應邊界的距離)
    ![Screen Shot 2022-05-01 at 9 54 44 AM](https://user-images.githubusercontent.com/59676941/166128890-dac453ef-059a-4ba3-86ca-9209195817ab.png)
4. 雖然桌面看不到那個navmenu，但是我相信這種東西之後會變成dropdown元件，桌面尺寸就會看到了；因為那些選項是可以點的東西，所以用`<button>`tag會比用`<li>`來得合適 (您想在li裡面放button也可以)
5. Figma上面忘記說了，小螢幕右邊那個navmenu按鈕應該要是一個ghost button才對
    真是太不應該了，抱歉patrick哥，您之後有空再把它改一改 https://i.redd.it/9q502ng4orw81.jpg，感謝patrick哥
    ![Screen Shot 2022-05-01 at 8 36 07 AM](https://user-images.githubusercontent.com/59676941/166128992-e15b3e12-4a4b-485a-8bf7-cfaa7ddcac6b.png)
6. sidemenu的圖片會露出底下的白色，這真是太巧妙的隱喻了patrick哥，處處是巧思
    ![Screen Shot 2022-05-01 at 8 32 10 AM](https://user-images.githubusercontent.com/59676941/166129263-765a50fc-81c0-4688-a775-69dc6230a254.png)

## Layout 指引

這是我們目前的mockup

![Screen Shot 2022-05-01 at 8 45 29 AM](https://user-images.githubusercontent.com/59676941/166127630-7bd36693-3343-4c6e-9580-25022f099805.png)

通常我在做layout的時候會依照幾個簡單的規則，供您參考：
- 先看大layout
  navbar的結構很簡單，就是左邊的logo(+小螢幕的sidebar toggle) -> 中間search-bar -> 右邊的功能按鈕三塊，很適合橫向flexbox+垂直置中；然後三個東西之間還要有間隔，所以還要加上 `justify-content: between或around` (通常是between，但是套用我們底下的作法之後兩種會得到一樣的效果)。
  所以我們就可以得到 `flex items-center justify-between` 這三個class。
- 接下來做padding，因為：
  - 絕大多數的東西都會有padding，而且x軸(左/右)通常一樣，y軸(上/下)也是。
  - 我們用 `box-sizing: border-box`，所以如果element有明確設置width/height，padding也會被包含在裡面，這樣padding就會變成像是盒子一樣把中間的內容圍起來，確保裡面的東西不會過長/過高。

  因此我們可以分析一下navbar的padding：
    - 在大螢幕中，x軸的padding是64px，y軸的padding是11px (看最高的element離邊緣有多遠，就是他的padding-y)。
    - 在小螢幕，x軸的padding是24px，y軸的padding還是11px。

  所以我們就會得到 `px-6 sm:p-16` 這兩個class，y軸的11px就看您想要怎麼做。
- 最後處理元素之間的間隔
  因為我們外層用的是flexbox，所以您可以直接用 [column-gap](https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap) 來解決，或是對著search-bar用x軸的margin也可以。
  另外在最大尺寸的設計下(1440px)search-bar的寬度是480px，所以我們還得替search-bar的container加上 `max-width: 480px`，然後用 `flex-grow: 1` 讓他自己把剩下的寬度填滿即可。

2022-05-01 02:54 UTC, abemscac commented on src/components/Portal.tsx
> +  return ReactDOM.createPortal(children, el.current)
這個不是問題，只是提一下
我們其實可以直接 `import { createPortal } from 'react-dom'`，看個人喜好

2022-05-01 02:54 UTC, abemscac commented on src/components/Portal.tsx
> +export default function Portal({ children }: Props) {
因為目前他只能幫我們把東西送到modal-root底下
所以建議您把它改名叫做ModalPortal什麼的，或是反過來把 `'modal-root'` 這個id當做props讓其他人傳進來，讓使用的人自己決定要把東西portal到哪裡

2022-05-01 02:54 UTC, abemscac commented on src/components/SidebarMobile.tsx
> +          （。人。）
阿斯
太精美了patrick哥，可以順便把點擊backdrop會關閉sidemenu的功能加上去

2022-05-01 02:54 UTC, abemscac commented on src/components/shared/Button.tsx
> +    : defaultButtonClass
這樣的寫法會在每次component re-render的時候重新計算這些變數的值
因為這裡有concat (跟for迴圈差不多意思)，所以建議用 `useMemo` 把它記起來，只在對應的參數更新的時候才去重新計算

2022-05-02 03:56 UTC, PatrickKuei commented on .eslintrc.json
> +    "jest/globals": true
報告史蒂芬哥
所以原來是卡在eslint跟jest性器不合嗎
阿斯 不愧是史蒂芬哥 配種達人 即使是巨_配上緊Ｏ 也能順利滑進去

2022-05-02 04:05 UTC, PatrickKuei commented on .vscode/settings.json
> +  "explorer.confirmDelete": false,
報告史蒂芬哥 我也不曉得怎麼有這個 可能每次刪檔案都要被問覺得太麻煩了吧
想Ｏ就Ｏ 想＿就＿ 問就是中共同路人 Ｇ🌟叵測 
![image](https://user-images.githubusercontent.com/48916128/166182838-21260db8-1653-4718-8599-1cc2e7902836.png)

2022-05-02 04:28 UTC, PatrickKuei commented on src/components/Home.tsx
> +}: Props) {
> * 我想這裡想寫的應該是 `export default function Home` 才對。

阿斯 不愧是史蒂芬哥 眼睛一如往常的銳利 鷹眼  大🦅

> * 目前我們只有HomeContainer + Home這個組合，所以這些狀態從上面傳下來沒問題；之後將navmenu和sidebar拆開變成獨立的component(或是其他作法)之後，您就必須思考這些屬性是否真的需要從上面傳下來，確保他不會被宣告在比他實際所需要還更高的階層中，以免state的值更新導致一整串不相干的component也跟著刷新。

我原本是想要試著拆成presentational component 和 container component
但好像拆的太早了史蒂芬哥
感覺應該和把元件抽出來的時候一起做 比較能考慮到哪些state要跟元件一起拿出來 放去哪 才能避免亂刷新的問題
現在看起來sideBarOpen和navMenuOpen這兩個state不應該放在HomeContainer
不然我為了開個sidebBar 整個home都刷新也太誇張 等等一起修正起來
感謝史蒂芬哥

2022-05-02 04:33 UTC, PatrickKuei commented on public/index.html
> +    <link href="/dist/output.css" rel="stylesheet" />
阿斯 報告史蒂芬哥 忘記刪掉了
那是第一次用tailwindcss的時候跟著官網上的[installation tailwind cli](https://tailwindcss.com/docs/installation)複製貼上的東西
後來才發現原來隔壁的[intallation tailwind CSS with create-react-app](https://tailwindcss.com/docs/guides/create-react-app)就可以直接用了
等等會一起刪掉
通通刪掉 就像會議記錄一樣通通刪掉

2022-05-02 04:48 UTC, PatrickKuei commented
另外報告史蒂芬哥
或許您已經知道這個問題了
我在用sourcetree和commitlint時有遇到無法直接使用sourcetree直接commit的狀況 都必須另外開terminal才能commit 很麻煩
後來是在~/.huskyrc加上 [這個東西](https://github.com/typicode/husky/issues/390#issuecomment-762213421) 才順利解決
驚 北市工程師霸氣用了那個東西 下場曝

2022-05-03 02:53 UTC, PatrickKuei commented on src/components/Portal.tsx
> +  return ReactDOM.createPortal(children, el.current)
沒問題史蒂芬哥
這邊在做的時候有遇到一個問題
一開始照著[官網](https://reactjs.org/docs/portals.html#usage)做 他會跳啥必須用react-dom-factory
後來另外用npm裝了那個東西之後才能使用createPortal
覺得怪 為啥create-react-app沒有包進去 感覺官網資訊也是過期的很慘

2022-05-03 03:01 UTC, PatrickKuei commented on src/components/Portal.tsx
> +export default function Portal({ children }: Props) {
阿斯 原來如此史蒂芬哥 看是要當香爐還是暖男
這個專案看起來都是modal會用到portal對吧史蒂芬哥 都是傳到root去顯示
不過話說回來除了傳到root以外還有其他用法嗎 比方說滑鼠點了巨Ｏ之後 下面水龍頭會打開開始漏水之類的 點擊Ａ 要把child傳到Ｂ下面的狀況？

2022-05-03 09:51 UTC, PatrickKuei commented on src/components/Home.tsx
> +      </div>
報告史蒂芬哥
今天莫名奇妙公司主管從早上開會開到現在完全沒有停
我也莫名其妙之後被排了一堆會議要參加 我隨意一睹 每週都５６個會 真的很無聊
然後不曉得是不是新的一季剛開始 功能都還在設計師那邊 主管只會叫我們investigate 也不知道要硬什麼 我的大懶鷲可能還比較硬

目前已經把史蒂芬哥您提到的１２３４５通通處理完了
６可能之後直接串ＡＰＩ 就不重新換mock image了 再也看不見白色小底褲了

不過關於３史蒂芬哥 容器固定24px icon大小不同的話 水平位置怎麼處理比較好
我看figma好像都是padding-left 3.25px 也不太像置中的樣子 我目前是先給pl-1 不曉得史蒂芬哥您怎麼看

另外關於共用元件Button的問題
我在想text only / text + icon / icon only 和各種組合加在一起會不會太多了 目前是模仿antd的使用來設計的
但再細分一點不曉得會不會更好

最後報告史蒂芬哥 有關點擊dialog外面關閉dialog的函式已經上網複製貼上了
不過在那些eventHandler, mouseEvent, Event, React.MouseEvent 還有啥addEventListener需要的native event之間的type搞得昏頭轉向 
最後我直接給type: any來暫時解決這一切 不曉得史蒂芬哥您對這部分有沒有了解

再麻煩史蒂芬哥您幫忙review了
![image](https://user-images.githubusercontent.com/48916128/166434150-55a31dd7-e93c-473c-9018-2b5b9f73e2c1.png)

2022-05-03 13:30 UTC, abemscac commented on .eslintrc.json
> +    "jest/globals": true
報告patrick哥
看log之前不通應該是因為commitlint在npm package伺服器因為不知道什麼原因壞了
所以那個套件一直裝不成功  就整個卡住了
不過現在正常了

2022-05-03 13:42 UTC, abemscac commented
報告patrick哥
最近真的太忙了  忙著提昇台灣價值
等有空的時候再來仔細欣賞您的回覆及大作
在此送上美圖一張  以示歉意
抱歉patrick哥

![IMG_20220502_191433](https://user-images.githubusercontent.com/59676941/166463814-d66909c3-450c-4125-a31a-e712b50bcd09.jpg)

2022-05-03 13:57 UTC, abemscac commented on src/components/Portal.tsx
> +  return ReactDOM.createPortal(children, el.current)
報告patrick哥
剛才試了一下  沒有看到那個怪問題
我把react-dom-factories從package.json刪掉 + node_modules資料夾 + yarn.lock通通刪起來
然後重新yarn install再執行  還是沒看見
也許您先前是遭受某黨派的網軍攻擊  所以他壞掉了
可以再試一次看看

2022-05-04 02:10 UTC, PatrickKuei commented on src/components/Portal.tsx
> +  return ReactDOM.createPortal(children, el.current)
原來是我們中華台北第四軍的攻擊嗎 太惡劣了 難怪我們華視最近每天出包 連四軍統帥都變成菜ＥＥ
沒問題史蒂芬哥 反正他現在能用了就行

2022-05-04 13:38 UTC, abemscac commented on src/components/Home.tsx
> +      </div>
報告patrick哥
奶圖真是太棒了  我愛釣魚

> 容器固定24px icon大小不同的話 水平位置怎麼處理比較好

Figma上面其實有兩個icon區塊  在Widgets裡面

![Screen Shot 2022-05-04 at 8 18 29 PM](https://user-images.githubusercontent.com/59676941/166687697-98781b6c-1585-432b-8206-bcf5630458c7.png)

這裡可以挑選您需要的icon  然後匯出成svg (您的匯出應該是在Inspect裡面)

![Screen Shot 2022-05-04 at 8 18 15 PM](https://user-images.githubusercontent.com/59676941/166687886-bc43817f-029e-4e32-af8e-76ce3012511d.png)

預設就是24x24  所以直接放到app裡面就可以用了
因為我們匯出svg  所以在app裡面用style改大小也不會失真
三圍想要多少就是多少  不囉嗦

> 共用元件Button的問題

我們的按鈕分成small/medium/large三個尺寸  用來決定裡面的icon和字的大小
variant用來決定主題(色調)
fillType用來決定按鈕的背景色/border/hover顏色等等
最後就是看他是不是沒有字  只有icon來決定他的長寬要不要設成一樣的

如果您覺得這個不好做的話  也可以直接把icon only的按鈕分出去變成自己的 `<IconButton />` 這種的

> 不過在那些eventHandler, mouseEvent, Event, React.MouseEvent 還有啥addEventListener需要的native event之間的> type搞得昏頭轉向

`Event`是javascript原生的東西  是所有事件的base interface
`MouseEvent`, `TouchEvent`這些也是javascript原生的東西
`MouseEvent`就如同他的名字所說  所有和滑鼠有關的事件(move/hover/click等等)都會用這個型態被擷取下來
`TouchEvent`則是觸控事件(手機/平板)
至於 `React.MouseEvent` 這種react事件也是以js原生事件為基底  只是上面動了一點手腳  我也不知道動了什麼手腳
不過操作起來和原生事件幾乎一模一樣  所以可以把它看成原生事件就好

2022-05-04 13:41 UTC, abemscac commented on .eslintrc.json
> +  "extends": ["plugin:react/recommended", "airbnb", "prettier"],
安裝 `eslint-config-prettier` 之後在這裡加上 `"prettier"`
就不會有那種prettier幫我換行  可是eslint不要我換行的怪問題了

2022-05-04 13:45 UTC, abemscac commented on src/components/SidebarMobile.tsx
> +function SidebarMobile({ onDismiss }: Props) {
因為sidebar打開之後就不會再打開了
所以我把 `onMobileMenuClick` 改成叫做 `onDismiss`

2022-05-04 13:48 UTC, abemscac commented on .eslintrc.json
> +    "jsx-a11y/no-static-element-interactions": "off"
因為那個什麼aria三小的真的太煩了patrick哥
所以我直接把它關掉  不然做很慢
東卡西卡  這樣也不行那樣也不行
就好像花8千喝好茶結果不給親不給摸  有夠賭爛

2022-05-04 13:48 UTC, abemscac approved these changes

2022-05-04 13:48 UTC, merged

2022-05-05 02:22 UTC, PatrickKuei commented on src/components/shared/Button.tsx
> +      {title}
報告是史蒂芬哥
我原本也打算這樣
但那時候button會丟一個錯誤說啥 `React.Children.only expected to receive a single React element child`
不過現在又不會了 真的很奇怪
上次的react-dom-factory也是 都重現不了
剛好我都用無痕在找資料 通通沒有記錄 還以為我在夢遊

2022-05-05 02:32 UTC, PatrickKuei commented on src/components/SidebarMobile.tsx
> +        >
報告是史蒂芬哥
我原本也是這樣想
但我在div上給onClick的話 他又會要我寫一大堆啥rule之類的
<img width="876" alt="image" src="https://user-images.githubusercontent.com/48916128/166855439-d8497053-83c1-48e9-9788-bb958281daa1.png">
還好這個能重現了

是因為有把aria關掉嗎 阿斯 不愧是史蒂芬哥 叫aria的臭女表就是該關進籠子裡懲罰 既然不給摸 那就都不要出來了

2022-05-05 02:36 UTC, PatrickKuei commented on src/components/SidebarMobile.tsx
> +function SidebarMobile({ onDismiss }: Props) {
不愧是史蒂芬哥 這雅思肯定滿分了吧
我都不知道可以命名onDismiss 只會取什麼家豪 淑芬 差點就忘記史蒂芬哥您是命名大師了
剛剛去查了一下 好像開關dialog的callback都叫做onDismiss嗎

2022-05-05 02:38 UTC, PatrickKuei commented on .eslintrc.json
> +  "extends": ["plugin:react/recommended", "airbnb", "prettier"],
這個真的超煩 像瘋子一樣整天叫我做Ａ又不準Ａ
馬上裝起來全部的洞我都要

2022-06-07 10:32 UTC, PatrickKuei reviewed
報告史蒂芬哥
剛剛在#11的時候才知道原來留言還要按submit
這是先前留的言 再請您過目