8 navs for guest
abemscac/inet-PatrickKuei pull request #9
Opened 2022-05-09 03:44 UTC by PatrickKuei

Close #8 

報告史蒂芬哥
我先把pr建起來 讓您能夠滾動式幫我修正修正

目前是將一些元件拆分 還有把邏輯元件跟畫面元件分開
這樣拆之後應該還不用用到memo之類的才是
再麻煩史蒂芬哥您檢查了

另外報告史蒂芬哥 在typescript和eslint上又遇到一個問題
<img width="865" alt="image" src="https://user-images.githubusercontent.com/48916128/167336932-4af6826b-4e5d-4472-99c3-cdf49295611d.png">
我不懂我只是宣告型別而已 為啥一直要我用它
目前是先用eslint-disable-next-line略過
不曉得史蒂芬哥您怎麼看

2022-05-10 14:04 UTC, abemscac requested changes
報告patrick哥  目前先這樣
另外建議您將components分類一下  共用的一類  頁面的一類
藍的一類  綠的一類  橘的一類  白的也一類
檔案管理方式不是太重要  好分辨就行

2022-05-10 23:04 UTC, abemscac commented on src/components/Dropdown.tsx
> +        <div className="bg-white shadow-drop rounded-lg absolute -right-6 desktop:hidden">
另外報告patrick哥
如果這是一個共用元件  這裡的`desktop:hidden`就可以跟會議記錄一樣通通刪掉
需要他藏起來的時候再把class傳下來給他就好

2022-05-10 23:29 UTC, abemscac commented on src/components/DropdownContainer.tsx
> +  }
另外報告patrick哥 v2.0
dropdown應該跟html的select一樣  打開之後再去點其他地方他就會自己關起來

2022-05-11 07:11 UTC, PatrickKuei commented on package.json
> +    "uuid": "^8.3.2",
沒問題史蒂芬哥 更臣又 更米分 更言贊

2022-05-11 07:11 UTC, PatrickKuei commented on src/components/Button.tsx
> +  variant?: 'primary' | 'secondary' | 'custom'
報告史蒂芬哥
我是想說這樣看起來比較一致 不會有些地方寫Button 有些寫button
或者如果要繼續用原生的button的話
那個Button改一下名字 可能叫InetButton之類的 會比較好區別？

2022-05-11 07:12 UTC, PatrickKuei commented on src/components/Button.tsx
>    icon: '',
報告史蒂芬哥
我原本也是這麼寫的 直到我又被那個eslint肛出血
<img width="769" alt="image" src="https://user-images.githubusercontent.com/48916128/167759521-02a75f82-abdb-4a98-b726-2fc3f5291b18.png">

不曉得是不是airbnb的限制？

2022-05-11 07:13 UTC, PatrickKuei commented on src/components/Dropdown.tsx
> +  DropdownEntryComponent: ReactElement
報告史蒂芬哥 對於命名很難我一直也很有感
剛好最近看到一句話

> There are only two hard things in Computer Science: cache invalidation and naming things.
> 
> -- Phil Karlton

真的是太男了

2022-05-11 07:55 UTC, PatrickKuei commented on src/components/Dropdown.tsx
> +  isDropdownOpen: Boolean
報告史蒂芬哥
所以會在自己元件內使用而且只會影響自己元件的變數 就可以用簡短命名嗎
我蠻習慣寫長但可以確保沒有誤會的命名了 比方說以後有菜雞接手維護 他看到簡短命名 就跟著省略亂寫 但他可能根本不是那個意思 或是別有意思
像我司常常同一個值會有3 4個名字
可能都是同一個來源 比方說都是從this.props取的 但在不同function裡面他就叫不同名字 然後傳下去到別的function裡面名字就越差越遠 最後匯聚到某一個元件 看起來就像不同來源來的 但不止值相同 其實根本就同一個 
每次都花很多時間去找去追蹤還要驗證到底一不一樣 能不能直接拿來用

不曉得史蒂芬哥您在用簡短命名的時候 通常怎麼避免這種事情發生？

2022-05-11 07:57 UTC, PatrickKuei commented on src/components/DropdownContainer.tsx
> +  }
> 另外這種container component / presentational component的實作方式我們丹大師以前也很喜歡 但是他後來不再推薦大家使用這套pattern了 也許您已經看過這篇文章了 https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0
> 
> 但是這種方式沒有不好 我認為他還是OK 多嘗試不同的方式也挺好 能接受的話可以用這套做下去看看

報告史蒂芬哥
說的也是 container component看起來跟custom hook真的差不多 hook還可以做到更多事
我這次想這樣寫寫看單純是因為我司全部都這樣寫 我很好奇這樣寫的優點到底是啥 讓他們這麼堅持
看來就只是群過氣老人不願學習新東西罷了

不過既然都寫了 我就先這樣寫下去 好好體驗一下全套按摩療程 林森北泰式頂級按摩

2022-05-11 08:18 UTC, PatrickKuei commented on src/components/Dropdown.tsx
> +        <div className="bg-white shadow-drop rounded-lg absolute -right-6 desktop:hidden">
有道理史蒂芬哥
共用元件應該不會有這種設定才對
就像採購什麼疫苗什麼快篩 人民的稅金幾億幾億花也都不該有會議紀錄一樣
要是被人發現政府偷偷做什麼見不得人的事情怎麼辦
為善不欲人知 為惡更不能被知
阿斯 有政府 會做事 色違小英

2022-05-11 09:21 UTC, abemscac commented on package.json
> +    "uuid": "^8.3.2",
報告是patrick哥
就像以前都用180大隻馬  試過之後發現150小隻馬也很讚
雖然體積更小  但是品質不輸  該大的大

2022-05-11 09:22 UTC, abemscac commented on src/components/Button.tsx
> +  variant?: 'primary' | 'secondary' | 'custom'
原來魯此patrick哥  有道理
當然沒問題  您方便就行

2022-05-11 09:53 UTC, abemscac commented on src/components/Button.tsx
>    icon: '',
報告看起來就是a兒逼&逼在搞鬼patrick哥
把它從.eslintrc.json移掉+plugins陣列多放一個 `"import"` 之後整個世界都清淨了
type宣告的callback參數不會再跟您說這個沒用到那個沒用到  那些什麼aria三小的也都消失了
我沒有仔細看過airbnb到底有哪些預設規則  不過目前的體驗不太好
差評  看我馬上就去airbnb房源給負評說 "因為eslint設定的太糟  欠噓"

2022-05-11 10:22 UTC, abemscac commented on src/components/Dropdown.tsx
> +  isDropdownOpen: Boolean
報告patrick哥  聽起來比較像是因為工程師本體素質差+完全沒有像樣的code review所造成的
都沒去看別人寫了什麼  根本沒花時間研究codebase
想加就加  然後直接就merge
這樣就算您的名字取得再好  這種慘劇最後一定還是會發生

---

以checkbox是否打勾當例子  通常就是取個 `(is)checked`
如果我們是在checkbox的component裡面  那 `checked` 這個名字就很清楚了
因為checkbox裡面除了那個box以外不會有第二個東西可以被checked  所以 `isCheckboxChecked` 就顯得多餘

但是如果我們是在一個表單的component  然後我們取了一個變數叫做 `isEmpty`  這時候他的意思就很模糊
因為表單裡面有很多欄位  幾乎每個都可以是empty  你說的是哪一個
例如單個的input/textarea/select  甚至是form本身都可以是 `isEmpty` 的對象(代表沒有任何一個欄位被填寫)
常見的還有 `visible`, `hidden`, `loading` 這種萬用的形容詞

---

我認為主要還是看這個變數宣告的地方+他代表的意思
如果我們宣告在一個範圍比較大的區塊  而且他可以用來形容很多東西  那變數命名就要盡量明確
如果我們的上下文已經很清楚了  這時候就可以選簡短的命名
不過不管在哪裡  我認為完全符合以下規則的就是好名字

- 明確
- 好理解
- 短的比長的更好，但是盡量不要縮寫 (例如`quantity / qty`, `length / l`, `count / cnt`)

2022-05-18 07:04 UTC, PatrickKuei commented on src/components/Dropdown.tsx
> +  overlay: Array<any>
> 然後我們自己用這個icon去找對應的svg或img路徑 例如 <img src={`../icons/${option.icon}.svg`} ... /> 怎樣的

報告史蒂芬哥 這些icon應該會是從api取對吧？
因為api doc網站好像掛掉了 我目前是先從前端資料夾取svg出來 當成react component直接用
我有試著用<img src={...}> 不過那個相對路徑有點奇怪 聽說要把圖片放在/public啥的
後來我試著import xxx from '../icons/xxx.svg'   然後丟進img src
結果整個css亂掉 也不知道為啥
後來我套回svg react component才恢復

如果這些圖片是從api叫的話 可能到時候串了再調整一下？

2022-05-18 07:10 UTC, PatrickKuei commented on src/components/Dropdown.tsx
> +              <li key={uuidv4()}>{item}</li>
沒有問題史蒂芬哥 通通刪掉
我那時候是參考[antd的dropdown](https://ant.design/components/dropdown/)下去寫的
確實props為主的比較好寫史蒂芬哥
光是弄DropdownItem就要額外想很多東西
然後也很想把那些Container拿掉 
目前寫成
> `<DropdownContainer
>         className="desktop:hidden"
>         toggleIcon={dropdownToggleIcon}
>       >
>         <DropdownItemContainer
>           title="Sign Up"
>           icon="signup"
>           onClick={onDropdownItemClick}
>         />
>         <DropdownItemContainer
>           title="Login"
>           icon="login"
>           onClick={onDropdownItemClick}
>         />
>       </DropdownContainer>`

一堆container
然後children還得多傳一層
看來真的是過氣了

2022-05-18 07:11 UTC, PatrickKuei commented on src/components/shared/DropdownContainer.tsx
> +function useOutsideHandler(ref: React.MutableRefObject<any>, handler: any) {
報告史蒂芬哥
為了實現點擊dropdown以外的時候可以關閉dropdown
我又把這個hook加回來了

這樣應該沒錯吧史蒂芬哥 因為dropdown沒有外層的div可以onClick了

2022-05-18 07:15 UTC, PatrickKuei commented on src/components/shared/DropdownContainer.tsx
> +      disabled={isOpened}
報告史蒂芬哥
這邊有個問題
目前打開dropdown之後 點選以外的區域時會觸發line: 47的setIsOpened(false)
但是如果點在打開dropdown的icon上時（這一個Toggle）
他就會先觸發line: 47 然後又觸發這邊的onClick
所以就關關開開 最後還是開的

我後來的想法是讓這個Toggle button 在isOpened = true的時候 disabled
來讓他不要關完又被打開
但最後還是不行 整天關關開開關關開開

感覺應該是跟propagation有關
不曉得史蒂芬哥您怎麼看

2022-05-18 07:20 UTC, PatrickKuei commented on src/components/shared/Dropdown.tsx
> +Dropdown.displayName = 'Dropdown'
報告史蒂芬哥
這邊也是esilnt吵著要我加的
說arrow function的宣告方式沒有displayName
不過要套上React.forwardRef的話我也只會這樣用

直接用之前的Function Dropdown(...){}的話不曉得怎麼把forwardRef加上去

2022-06-01 05:12 UTC, abemscac approved these changes
看起來挺好的patrick哥  沒什麼大問題
我修改了一些東西  等等放在留言裡面

2022-06-01 05:13 UTC, abemscac commented on package.json
> -    "uuid": "^8.3.2",
我們有ㄋㄟno id了
所以我把悠悠id刪掉
目前看起來都沒用到

2022-06-01 05:14 UTC, abemscac commented on src/components/pages/Navbar.tsx
> +import { SearchIcon } from '../../icons'
Icon我把icon都移到同個地方去了
會在下面解釋

2022-06-01 05:17 UTC, abemscac commented on src/components/shared/Button.tsx
>  }
原本 `type` 是給 `fillType` 用的
但是html的button也有一個 `type`，常用的是 `button` (這個是預設值) 和 `submit`
<button type="submit">常常放在form裡面  相信您已經看過很多次了
為了避免將來的衝突  我把type改成fillType

另外也加上了一些預設值的jsdoc
這樣如果有人寫<Button variant="...">  然後把滑鼠移到variant上面
他就可以看到這個屬性的預設值是什麼

2022-06-01 05:25 UTC, abemscac commented on src/components/shared/DropdownContainer.tsx
> -
我把這個hook移出去了
變成一個獨立的hook  將來需要的話可以共用
這裡有個問題  就是effect的dependencies用ref
ref是永遠不會改變的  ref.current才會變 (可以參考這個範例 https://stackblitz.com/edit/react-wtjtey?file=src%2FApp.js)
所以這樣寫的話他就只有mounted的時候把handler綁上去  之後handler怎麼變都不會影響到document的eventListener
代表如果handler function裡面有一些依據state來做判斷的邏輯  他就不會正常運作了  因為listener沒有重新remove -> add
因此這裡的dependency放handler比較正確
還有一些小東西  您可以看看那個useClickOutside的hook

2022-06-01 05:28 UTC, abemscac commented on src/components/shared/DropdownContainer.tsx
> +  useClickOutside(wrapperRef, handleOutsideClicked)
用useCallback把handleOutsideClicked包起來的原因是我們原本是寫arrow function
代表每次畫面re-render他都會重新宣告一個新的function給他
就會觸發到hook裡面的effect
雖然目前應該不會有什麼效能問題  但是感覺上不太好

2022-06-01 05:30 UTC, abemscac commented on src/icons/index.ts
> +export { LoginIcon, MenuIcon, SearchIcon, SignUpIcon, UserIcon }
我把唉孔都移到這裡來了
這樣DropdownItem他們就可以用同一個type  不用各自寫icon props允許哪些值
另外同時輸出IconMap和個別的icon  需要哪個就用哪個

2022-06-01 05:42 UTC, abemscac approved these changes
另外目前我們是用../../icons這樣的import
可以把它改成~/icons或是@inet/icons這種的import
之後再說

2022-06-01 05:42 UTC, merged